name: Build / Containerize

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2

      - name: Publish
        run: dotnet publish --os linux --arch x64 -c Release -p:PublishProfile=DefaultContainer

      #- name: Log in to Docker Hub
      #  uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      #  with:
      #    username: ${{ secrets.DOCKER_USERNAME }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: |
            caesay/docker-pomerium-launcher

      #- name: Build and push Docker images
      #  uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      #  with:
      #    context: .
      #    push: true
      #    tags: ${{ steps.meta.outputs.tags }}
      #    labels: ${{ steps.meta.outputs.labels }}